@BestOfHackerNews_HostAddress = https://localhost:55002

#Set an api key value to the environment of the running service before executing this sample call

GET {{BestOfHackerNews_HostAddress}}/beststories/5
Accept: application/json
X-API-Key: test
